name: deepsafe_api_v1
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.3.29=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - chardet==3.0.4
    - click==8.1.2
    - flask==2.0.2
    - idna==2.10
    - itsdangerous==2.1.2
    - jinja2==3.1.1
    - jsonpickle==2.0.0
    - markupsafe==2.1.1
    - numpy==1.22.3
    - opencv-python==4.5.5.64
    - pillow==9.1.0
    - requests==2.24.0
    - torch==1.9.0
    - torchvision==0.10.0
    - typing-extensions==4.1.1
    - urllib3==1.25.11
    - werkzeug==2.1.1
prefix: /home/siddharth/miniconda3/envs/deepsafe_api_v1
