# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and contents sections (<content full_path="...">...</content>)
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"
  - "examples/"
  - "MANIFEST.in"
  - "setup.py"
  - "frontend/node_modules/**"
  - "models/image/cnndetection/cnndetection/**"
  - "models/image/ganimagedetection/ganimagedetection/**"
  - "models/image/universalfakedetect/universalfakedetect/**"
  - "assets/**"
  - "frontend/package-lock.json"

# Ignore files and directories for contents sections
ignore-content:
  - "README.md"
  - "LICENSE"
  - "tests/"