# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and contents sections (<content full_path="...">...</content>)
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"
  - "examples/"
  - "MANIFEST.in"
  - "setup.py"
  - "frontend/node_modules/**"
  - "models/image/cnndetection/cnndetection/**"
  - "models/image/ganimagedetection/ganimagedetection/**"
  - "models/image/universalfakedetect/universalfakedetect/**"
  - "models/image/hifi_ifdl/hifi_ifdl/**"
  - "assets/**"
  - "frontend/package-lock.json"
  - "hifi_ifdl/**"
  - "models/image/hifi_ifdl/repo-to-text_2025-05-02-08-05-22-UTC.txt"
  - "models/image/caddm/caddm/**"
  - ".venv/**"
  - "frontend/public/images/demo_image.jpg"
  - "frontend/public/favicon.png"
  - "models/image/caddm/**"
  - "models/image/dmimagedetection/**"
  - "models/image/hifi_ifdl/**"
  - "models/image/npr_deepfakedetection/**"
  - "models/image/universalfakedetect/**"
  - "experiments/**"
  - "experiment_output/**"
  - "experiment_output_0.3/**"
  - "experiment_output_0.5/**"



# Ignore files and directories for contents sections
ignore-content:
  - "README.md"
  - "LICENSE"
  - "tests/"