name: deepsafe_v6
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.1.0=gpu
  - aiohttp=3.8.1=py38h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38hd667e15_1
  - click=8.0.4=py38h06a4308_0
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - dataclasses=0.8=pyh6d0b6a4_7
  - frozenlist=1.2.0=py38h7f8727e_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.19.1=h4ff587b_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=5.2.0=py38h7f8727e_2
  - ncurses=6.3=h7f8727e_2
  - numpy-base=1.21.2=py38h79a1101_0
  - oauthlib=3.2.0=pyhd3eb1b0_0
  - openssl=1.1.1n=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pip=21.2.4=py38h06a4308_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.0=hc218d9a_0
  - tensorflow-base=2.4.1=gpu_py38h29c2da4_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - tensorflow-gpu=2.4.1=h30adc30_0
  - tk=8.6.11=h1ccaba5_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==1.0.0
    - albumentations==1.1.0
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - asttokens==2.0.5
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - blinker==1.4
    - bokeh==2.4.1
    - boto3==1.21.27
    - botocore==1.24.27
    - brotli==1.0.9
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dface==1.1.5
    - dlib==19.23.1
    - docopt==0.6.2
    - efficientnet-pytorch==0.7.1
    - einops==0.4.1
    - entrypoints==0.4
    - executing==0.8.3
    - face-recognition==1.3.0
    - face-recognition-models==0.3.0
    - facenet-pytorch==2.5.2
    - ffmpeg-python==0.2.0
    - fonttools==4.31.1
    - future==0.18.2
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - h5py==3.6.0
    - htbuilder==0.6.0
    - imageio==2.16.1
    - importlib-metadata==4.11.3
    - importlib-resources==5.4.0
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - iteration-utilities==0.11.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - jmespath==1.0.0
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - keras==2.8.0
    - kiwisolver==1.4.0
    - libclang==13.0.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - munch==2.5.0
    - mutagen==1.45.1
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - networkx==2.7.1
    - notebook==6.4.10
    - numpy==1.22.2
    - opencv-python==4.5.5.62
    - opencv-python-headless==4.5.5.64
    - packaging==21.3
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pipreqs==0.4.11
    - plotly==5.6.0
    - pretrainedmodels==0.7.4
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==7.0.0
    - pyasn1-modules==0.2.8
    - pycryptodomex==3.14.1
    - pydeck==0.7.1
    - pygments==2.11.2
    - pympler==1.0.1
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytube==12.0.0
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - s3transfer==0.5.2
    - scikit-image==0.17.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - streamlit==1.7.0
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tifffile==2022.3.16
    - timm==0.5.4
    - toml==0.10.2
    - toolz==0.11.2
    - torch==1.10.2
    - torchvision==0.11.3
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - tzdata==2022.1
    - tzlocal==4.1
    - urllib3==1.26.9
    - validators==0.18.2
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websockets==10.2
    - werkzeug==2.1.0
    - widgetsnbextension==3.6.0
    - wrapt==1.14.0
    - yarg==0.1.9
    - you-get==0.4.1555
    - youtube-dl==2021.12.17
    - yt-dlp==2022.3.8.2
prefix: /home/siddharth/miniconda3/envs/deepsafe_v6
